### PR TITLE
lib: Return size in write functions

### PR DESCRIPTION
**Pull request by nmsv**
Returning size of written payload is usually a sane thing to do. Shouldn't hurt anyone.

### CODE REVIEW

**Review by patrickelectric — APPROVED** [review]

**Comment by patrickelectric** [comment]
It appears that something is wrong with GitHub, I can't get the "approve and run" button to work since it redirects to page 500 error. Will try again later.

**Comment by mrpollo** [comment]
Can't get it to work for me either not sure what's going on.

**Comment by hamishwillee** [comment]
Same, does not work. You might have to contact github.

**Comment by mrpollo** [comment]
I opened a support ticket with GitHub, I'll post back

**Comment by mrpollo** [comment]
@patrickelectric not sure if #97 helped unblock things or if my support ticket, but CI is running, but failing, on an error that I can't really understand, I'll leave it to someone smarter than me to figure it out

**Comment by mrpollo** [comment]
@nmsv looks like CI is reporting a real error

```
     Running `/home/runner/work/rust-mavlink/rust-mavlink/target/debug/deps/process_log_files-6ac8326e72b327a0 --nocapture`
running 1 test
Processing file: /tmp/testlogs/ArduCopter-test.tlog
thread 'process_files::all' panicked at 'Unable to hit the necessary amount of matches', tests/process_log_files.rs:71:9
recv error: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Number of parsed messages: 0
test process_files::all ... FAILED

failures:

failures:
    process_files::all


test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.57s

error: test failed, to rerun pass '--test process_log_files'
```

**Comment by nmsv** [comment]
@mrpollo
@patrickelectric 
@hamishwillee 

I'm able to reproduce the failed test on master (91f3966):
`cargo test --verbose --features all-dialects -- --nocapture`
So, as far as I understand, this is not related to the PR.

**Comment by patrickelectric** [comment]
Merged in #100

**Pull request closed without merging**
