### PR TITLE
travis: Add deploy via cargo with tags

### PR DESCRIPTION
**Pull request by patrickelectric**
@podhrmic Can you create a secure travis token and share it with me to add in the file ?
https://docs.travis-ci.com/user/encryption-keys/

I prefer this online website to do it: https://travis-encrypt.github.io/
but you can use the travis official link to generate it

### CODE REVIEW

**Comment by patrickelectric** [comment]
Also, can we do a minor release ?

**Comment by podhrmic** [comment]
I am not sure I understand what are the keys for? So cargo can use travis for testing?

**Comment by podhrmic** [comment]
> Also, can we do a minor release ?

I assume you mean after merging #40? I think we sure can.

**Comment by patrickelectric** [comment]
@podhrmic with the variable it'll deploy the package via cargo to crates.io automatically

**Comment by podhrmic** [comment]
OK, it turns out I don't have permissions to do so:-/ Perhaps @kevinmehall or @tstellanova has the rights?

**Comment by kevinmehall** [comment]
@podhrmic You have the same level of access I do at https://crates.io/crates/mavlink/owners.

If you decide to do this, you should consider making a separate account for it. As far as I know crates.io tokens aren't scoped to a particular package, so it would be able to publish to any of your packages.

**Comment by podhrmic** [comment]
OK, this should be fixed with https://github.com/mavlink/rust-mavlink/commit/c975d078e5444114f3f608dc0cb72e2c177d8b75

I created a new account for that, encrypted the token as mentioned and added it to `.travis.yml`

I still had to manually push a new 0.8 tag.

I will close this PR once travis builds and hopefully pushes the new version to crates.

**Comment by podhrmic** [comment]
0.8 released! The travis->cargo seems to work for tagged releases, but in this case it failed on some internal travis error. So I did the release manually.

**Pull request closed without merging**
