### PR TITLE
align MSRV check with 'rust-version'

### PR DESCRIPTION
**Pull request by danieleades**
the MSRV check should match the 'rust-version' specified in `Cargo.toml`

### CODE REVIEW

**Comment by danieleades** [comment]
as you can see from the failed test, the `rust-version` in `Cargo.toml` is not correct. I'll have to bump the version to get this to build

**Comment by danieleades** [comment]
i've left the commits in there for ease of review, but you probably want to squash merge this

**Comment by patrickelectric** [comment]
Thanks @danieleades, can you squash the commits ? We don't have squash merge enable for better descriptive commit messages.

**Comment by danieleades** [comment]
> Thanks @danieleades, can you squash the commits ? We don't have squash merge enable for better descriptive commit messages.

What is the impact on commit messages of using github's squash merge? It gives you the option of setting the commit message when you merge, no?

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
