### PR TITLE
Add bindings for ardupilotmega.xml 

### PR DESCRIPTION
**Pull request by frizensami**
This patch adds bindings for messages defined in ardupilotmega.xml. XML data was manually copied and pasted into combined.xml - perhaps this could be automated in the future.

### CODE REVIEW

**Comment by frizensami** [comment]
wat

Been testing it with Arducopter software-in-the-loop: seems to be detecting the new messages appropriately.

**Comment by podhrmic** [comment]
Probably obsolete, as it is trivial to add additional xml files to parse, but it is unclear whether it is something we should do.

**Comment by hamishwillee** [comment]
Hi @podhrmic The general model for all our other generators is that they take mavlink version and one or more dialects as inputs, and generate libraries for the specified dialect.

For pre-built versions the model (at least for C and Python) is to generate libraries for all dialects in mavlink/mavlink and include them in the package.

While I don't understand what this code is doing, I suggest you try emulate that approach.

**Comment by laptou** [comment]
This PR is covered by #40, consider closing it when 40 is merged? @patrickelectric

**Pull request closed without merging**
