### PR TITLE
Refactor/code gen

### PR DESCRIPTION
**Pull request by danieleades**
this PR makes the generated code more idiomatic. Silences a whole bunch of clippy lints in the generated code.

This PR also adds clippy and rustfmt CI targets. Would be good to get some feedback on what features matrix should be used for clippy here?

### CODE REVIEW

**Comment by patrickelectric** [comment]
@danieleades I'm a bit in a rush and I'm trying to review and merge as much PRs as possible since I'm going to be in vacation in the middle of next week. 
Be free to ping me as many time as necessary for review. I should review this PR this week.

**Comment by danieleades** [comment]
No worries man. No rush

**Comment by patrickelectric** [comment]
@danieleades what is the status ?

**Comment by danieleades** [comment]
> @danieleades what is the status ?

Mostly just waiting on review. It's been a while, so I might need to give it a once over and a rebase

**Comment by danieleades** [comment]
@patrickelectric this should be ready for review now

**Comment by patrickelectric** [comment]
@danieleades thanks! I'll do the review tomorrow, please ping me otherwise.

**Comment by patrickelectric** [comment]
Can you squash all commits for us to merge ? Since the commits are kind of doing the same thing, it makes more sense to have a single commit for everything.

**Comment by danieleades** [comment]
@patrickelectric, no problem. That's squashed now.

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
