### PR TITLE
Implement ToPrimitive on enums

### PR DESCRIPTION
**Pull request by laptou**
- Adds `ToPrimitive` derive macro to enums so that they can be converted to primitives

### CODE REVIEW

**Comment by patrickelectric** [comment]
Hi @laptou can you rebase this PR over master or only cherry pick the necessary commit ?
There is 7 commits to only add `ToPrimitive` derivation, I believe that should be only a single commit

**Comment by laptou** [comment]
I don't know why there are several commits, but I already merged `mavlink:master` into my fork in 
`8eb914c`.

**Comment by patrickelectric** [comment]
You need to do `git rebase origin/master` if origin is this repository and not your fork.
or you can `git checkout origin/master`, `git checkout -b my_pr`, `git cherry-pick 5bf8cf7117386097d0581933c2b3c21dd2e2d44e` and create a PR with only the specific commit

**Comment by laptou** [comment]
Fixed @patrickelectric

**Comment by patrickelectric** [comment]
Hi @laptou, can you squash 412f1e6 with 1614b13 ? Since the second appears to be a fix for the first one.

**Comment by laptou** [comment]
Done

**Comment by patrickelectric** [comment]
Thanks!

**Pull request merged**
