### PR TITLE
Refactor/lints

### PR DESCRIPTION
**Pull request by danieleades**
I started with the goal of making clippy a little quieter, and ended up addressing a bunch of other low-hanging fruit while i was at it.

### CODE REVIEW

**Comment by patrickelectric** [comment]
Hi @danieleades, be free to squash and rebase your work

**Comment by danieleades** [comment]
@patrickelectric - done!

**Comment by patrickelectric** [comment]
@danieleades can you rebase over our current master branch ? We merged a couple of PRs that broke this one.

**Comment by danieleades** [comment]
@patrickelectric - this should be good to go

**Comment by danieleades** [comment]
see also #129

**Review by patrickelectric — APPROVED** [review]
great work!

**Pull request merged**
